version: '3.9'

services:
  web:
    build:
      context: ./web
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=supersecretkey
      - DJANGO_ALLOWED_HOSTS=*
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
  
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB:postgres
      POSTGRES_USER:postgres
      POSTGRES_PASSWORD:postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data